# Generated by Django 2.1.7 on 2019-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_auto_20190331_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerinfo',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
