# Generated by Django 2.1.7 on 2019-04-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=50)),
                ('topic', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
