# Generated by Django 2.1.7 on 2019-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='trainerinfo',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
